server:
  port: 8082

spring:
  application:
    name: showTime-service

  config:
    import: "optional:configserver:"

  datasource:
    url: ${DB_SHOWTIME_URL}
    username: ${DB_SHOWTIME_USER}
    password: ${DB_SHOWTIME_PASS}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  instance:
    prefer-ip-address: true
    hostname: showtime-service
    instance-id: showtime-service:8082
    non-secure-port: 8082

# ✅ Configuración básica de Feign (sin circuit breaker por ahora)
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic  # Cambia a 'full' si quieres ver más detalles en los logs

# ✅ Logging para debug (opcional, puedes comentar después)
logging:
  level:
    com.cinema.imax_showTime_service: DEBUG
    com.cinema.imax_showTime_service.client: DEBUG