server:
  port: 8082

spring:
  application:
    name: showTime-service

  config:
    import: "optional:configserver:"

  datasource:
    url: ${DB_SHOWTIME_URL}
    username: ${DB_SHOWTIME_USER}
    password: ${DB_SHOWTIME_PASS}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  instance:
    prefer-ip-address: false
    hostname: showtime-service
    instance-id: showtime-service:8082
    non-secure-port: 8082