server:
  port: 8082

spring:
  application:
    name: imax-showtime-service

  config:
    import: "optional:configserver:"

  datasource:
    url: ${DB_SHOWTIME_URL}
    username: ${DB_SHOWTIME_USER}
    password: ${DB_SHOWTIME_PASS}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    non-secure-port: 8082

# Basic feign config. (without circuit breaker, for now :) )
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic  #'full' if you want to see more details.

logging:
  level:
    com.cinema.imax_showTime_service: DEBUG
    com.cinema.imax_showTime_service.client: DEBUG