server:
  port: 8082

spring:
  application:
    name: showTime-service

  config:
    import: "optional:configserver:"

  datasource:
    url: jdbc:postgresql://localhost:5433/showtimedb
    username: showtimeuser
    password: secretpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
