server:
  port: 8761

spring:
  application:
    name: msvc-eureka
  config:
    import: optional:configserver:http://config-server:8888

eureka:
  instance:
    hostname: eureka-server
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/