# Usar este perfil cuando ejecutes desde tu IDE
spring:
  config:
    activate:
      on-profile: local

  # ==================== DATABASE LOCAL ====================
  datasource:
    url: jdbc:postgresql://localhost:5432/catalog_db
    username: cataloguser
    password: secretpassword

  # ==================== KAFKA LOCAL ====================
  kafka:
    # IMPORTANTE: Desde tu máquina (IDE) usa localhost:29092
    bootstrap-servers: localhost:29092

# ==================== EUREKA LOCAL ====================
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# ==================== TMDB API ====================
tmdb:
  api-key: e45bf974933312d09cde8e94a203b900


# ==================== LOGGING PARA DEBUG ====================
logging:
  level:
    org.apache.kafka: DEBUG
    org.springframework.kafka: DEBUG
    com.cinema.imax_catalog_service: DEBUG