server:
  port: 8081

spring:
  application:
    name: imax-catalog-service

  config:
    import: "optional:configserver:"

  datasource:
    url: ${DB_CATALOG_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  instance:
    prefer-ip-address: true   # mejor usar IP real que hostname inventado
    instance-id: ${spring.application.name}:${server.port}
    non-secure-port: 8081

tmdb:
  api-key: ${TMDB_API_KEY}
  base-url: https://api.themoviedb.org/3