server:
  port: 8081

spring:
  application:
    name: imax-catalog-service

  config:
    import: "optional:configserver:"

  datasource:
    url: ${DB_CATALOG_URL}
    username: ${DB_CATALOG_USER}
    password: ${DB_CATALOG_PASS}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

tmdb:
  api-key: ${TMDB_API_KEY}
  base-url: https://api.themoviedb.org/3